--- 
- name: Create Directory structure
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/opt/{{ service }}/config"
    - "/opt/{{ service }}/logs"

- name: "Start Docker service"
  service:
    name: docker
    state: started
    enabled: yes
    
- name: "error lock"
  shell: sudo apt -qy update 2>/dev/null | grep packages | cut -d '.' -f 1

- name: "installing pcks"
  become: true
  shell: sudo apt-get install -qy python&& sudo apt-get install -qy python3&& sudo apt-get install -qy python-pip&& sudo pip install docker
    

