--- 
- name: Create Directory structure
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/opt/{{ service }}/config"
    - "/opt/{{ service }}/logs"

- name: "Start Docker service"
  service:
    name: docker
    state: started
    enabled: yes
- name: create docker group
  become: true
  group:
    name: docker
    state: present

- name: add user to group 
  become: true
  user:
    name: "ubuntu"
    groups: docker
    append: true
           # <--- must do this if using pipelining

#- name: restart machine
 # shell: sudo reboot
##### setup ansible <---> docker


- name: killing
  shell: sudo killall apt apt-get

- name: Update all packages to the latest version
  apt:
    dpkg_options: 'force-confold,force-confdef'
    upgrade: dist
    
- name: Stop services
  service:
    name: "{{ item }}"
    enabled: no
  with_items:
    - apt-daily
    - apt-daily.timer
    - apt-daily-upgrade
    - apt-daily-upgrade.timer

- name: Disable services
  service:
    name: "{{ item }}"
    enabled: no
  with_items:
    - apt-daily
    - apt-daily.timer
    - apt-daily-upgrade
    - apt-daily-upgrade.timer

- name: install python dependencies
  become: true
  shell: apt install -y python3-pip

- name: install 'Docker SDK for Python'
  pip:
    name: docker
