--- 
- name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
  wait_for:
    port: 22
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    search_regex: OpenSSH
    delay: 10
  vars:
    ansible_connection: local
    
- name: Create Directory structure
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/opt/{{ service }}/config"
    - "/opt/{{ service }}/logs"

- name: "Start Docker service"
  service:
    name: docker
    state: started
    enabled: yes
    
