--- 
- name: Create Directory structure
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/opt/{{ service }}/config"
    - "/opt/{{ service }}/logs"

- name: "Start Docker service"
  service:
    name: docker
    state: started
    enabled: yes
    
- name: "installing pcks"
  become: yes
  shell: sudo apt -qy update&& sudo apt install -qy python3&& sudo apt install -qy python&& sudo apt install -qy python-pip&& sudo pip install docker-py
    
- name: "error lock"
  shell: sudo apt update 2>/dev/null | grep packages | cut -d '.' -f 1
