---
- name: Pre Tasks
  hosts: name_Packer_Builder
  gather_facts: false
  become: yes

  tasks:
    - name: Stop servicess
      service:
       name: "{{ item }}"
       enabled: no
      with_items:
       - apt-daily
       - apt-daily.timer
       - apt-daily-upgrade
       - apt-daily-upgrade.timer

    - name: "Install Docker"
      apt:
        name: docker.io
        state: latest
        update_cache: yes
      become: yes

    - name: install python dependencies
      shell: apt install -y python3-pip
      
    - name: install 'Docker SDK for Python'
      pip:
        name: docker
