---
- name: Pre Tasks
  hosts: name_Packer_Builder
  gather_facts: false

  tasks:
    - name: "Install Docker"
      apt:
        name: docker.io
        state: latest
        update_cache: yes
      become: yes