---

      
#- name: Upgrade all packages to the latest version
 # apt:
  #  name: "*"
   # state: latest
   # force_apt_get: yes  

         
- name: Start Container
  docker_container:
       name: "{{ service }}"
       image: "rozdockerforever/dev:{{ service }}_{{ service_version }}"
       pull: true
       recreate: yes
       ports:
         - "{{ api_port }}:{{ api_port }}"
       volumes:
         - "/opt/{{ service }}/config:/usr/src/app/config"
       restart_policy:
         unless-stopped
       interactive:
         no
       state:
         started
         
#- name: Save Docker Log Into Register
#  shell: docker inspect --format={{ '{{.State.Running}}' }} {{ service }}
#  register: docker_inspect
  
#- debug:
#    var: docker_inspect.stdout
      
- name: Get infos on container
  docker_container_info:
    name: "{{ service }}"
  register: result
 
- debug:
    msg: "{{ result }}"

- name: Does container exist?
  debug:
    msg: "The {{service}} container {{ 'exists' if result.exists else 'does not exist' }}"

- name: Print the status of the container
  debug:
    msg: "The {{service}} container status is {{ result.docker_container['State']['Status'] }}"
  when: result.exists
