---
- name: Copy Configuration file
  copy:
    src: "files/{{item}}"
    dest: "/opt/{{ service }}/config"
  with_items:
    - database.js
    - ntapi_1.0.0.tar
    
#- name: Execute the command in remote shell; stdout goes to the specified file on the remote.
 # shell: docker build -t "{{ service }}:{{ service_version }}" ./roles/"{{service}}/{{ service }}_{{ service_version }}".tar
# - name: Build image
#   docker_image:
#     name: "{{ service }}_{{ service_version }}"
#     state: present
#     path: "/opt/{{ service }}/config"
  
- name: Start Container
  docker_container:
    name: "{{ service }}"
    image: "{{ service }}_{{ service_version }}"
    recreate: yes
    ports:
      - "3000:3000"
    volumes:
      - "/opt/{{ service }}/config:/usr/src/app/config"
    restart_policy:
      unless-stopped
    interactive:
      no
    state:
      started
