---
  - name: Copy Configuration file
    copy:
      src: "files/database.js"
      dest: "/opt/{{ service }}/config"    

  - name: Start Container
    docker_container:
      name: "{{ service }}"
      image: "rozdockerforever/dev:{{ service }}_{{ service_version }}"
      pull: true
      recreate: yes
      ports:
        - "3000:3000"
      volumes:
        - "/opt/{{ service }}/config:/usr/src/app/config"
      restart_policy:
        unless-stopped
      interactive:
        no
      state:
        started
      
      
  - name: Save Docker Log Into Register
    shell: docker inspect --format={{ '{{.State.Running}}' }} {{ service }}
    register: docker_inspect

  - debug:
      var: docker_inspect.stdout
      
  - name: debug facts
    set_fact:
      msg: the container "{{ service }}" is running "{{docker_inspect.stdout}}"
     when: "'true' in docker_inspect.stdout"



