---
  hosts: "Service_{{ service }}"
  gather_facts: false
  
- name: Pre Tasks
  pre_tasks:
     - raw: sudo apt-get -y install python-simplejson
       register: py_simple_output
     - raw: sudo apt-get -y install python-minimal
       register: py_minimal_output
     - raw: sudo apt-get update
       register: system_output
       
- name: Copy Configuration file
  copy:
    src: "files/database.js"
    dest: "/opt/{{ service }}/config"    

- name: Start Container
  docker_container:
    name: "{{ service }}"
    image: "rozdockerforever/dev:{{ service }}_{{ service_version }}"
    pull: true
    recreate: yes
    ports:
      - "3000:3000"
    volumes:
      - "/opt/{{ service }}/config:/usr/src/app/config"
    restart_policy:
      unless-stopped
    interactive:
      no
    state:
      started
      
- name: Get infos on container
  docker_container_info:
    name: "{{ service }}"
  register: result

- name: Does container exist?
  debug:
    msg: "The container {{ service }} {{ 'exists' if result.exists else 'does not exist' }}"

- name: Print the status of the container
  debug:
    msg: "The container {{ service }} status is {{ result.container['State']['Status'] }}"
  when: result.exists

