---
- name: Copy Configuration file
  copy:
    src: files/database.js
    dest: "/opt/{{ service }}/config"

- name: Start Container
  docker_container:
    name: "{{ service }}"
    path: "/var/jenkins_home/{{ service }}_{{ service_version }}.tar"
    image: "{{ service }}:{{ service_version }}"
    recreate: yes
    ports:
      - "3000:3000"
    volumes:
      - "/opt/{{ service }}/config:/usr/src/app/config"
    restart_policy:
      unless-stopped
    interactive:
      no
    state:
      started
