---
- name: Copy Configuration file
  copy:
    src: "files/database.js"
    dest: "/opt/{{ service }}/config"    

- name: Start Container
  docker_container:
    name: "{{ service }}"
    image: "rozdockerforever/dev:{{ service }}_{{ service_version }}"
    pull: true
    recreate: yes
    ports:
      - "3000:3000"
    volumes:
      - "/opt/{{ service }}/config:/usr/src/app/config"
    restart_policy:
      unless-stopped
    interactive:
      no
    state:
      started
      
- name: checking-running Container
docker inspect --format={{ '{{.State.Running}}' }} {{service}}
  shell: docker inspect -f "{{.State.Running}}" "{{service}}"
  register: status

- debug:
    var: status.stdout

- set_fact:
        stop_enabled: true
  when: "true" == status.stdout

- fail:
    msg: "FAIL ,The Conteiner is NOT running"
  when: "false" == status.stdout
