---
- name: Copy Configuration file
  copy:
    src: "files/database.js"
    dest: "/opt/{{ service }}/config"    

- name: Start Container
  docker_container:
    name: "{{ service }}"
    image: "rozdockerforever/dev:{{ service }}_{{ service_version }}"
    pull: true
    recreate: yes
    ports:
      - "3000:3000"
    volumes:
      - "/opt/{{ service }}/config:/usr/src/app/config"
    restart_policy:
      unless-stopped
    interactive:
      no
    state:
      started
      
- name: checking-running Container
  shell: docker inspect -f {{.State.Running}} {{service}}
  register: docker_log

- debug:
    var: docker_log.stdout

- set_fact:
        stop_enabled: true
  when: "true == docker_log.stdout"

- fail:
    msg: "FAIL ,The Conteiner is NOT running"
  when: " false == docker_log.stdout"
