---
- name: Copy Configuration file
  copy:
    src: "files/database.js"
    dest: "/opt/{{ service }}/config"    

- name: Start Container
  docker_container:
    name: "{{ service }}"
    image: "rozdockerforever/dev:{{ service }}_{{ service_version }}"
    pull: true
    recreate: yes
    ports:
      - "3000:3000"
    volumes:
      - "/opt/{{ service }}/config:/usr/src/app/config"
    restart_policy:
      unless-stopped
    interactive:
      no
    state:
      started
      
- name: Get infos on container
  docker_container_info:
    name: "{{ service }}"
  register: result

- name: Does container exists?
  debug:
    msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

- name: Print the status of the container
  debug:
    msg: "The container status is {{ result }}"
  when: result.exists

