---
- name: Copy Configuration file
  copy:
    src: files/.env
    dest: "/opt/{{ service }}/config"

- name: Start Container
  docker_container:
    name: "{{ service }}"
    image: "rozdockerforever/dev:{{ service }}_{{ service_version }}"
    recreate: yes
    ports:
      - "{{ web_port }}:{{ web_port }}"
    volumes:
      - "/opt/{{ service }}/config/.env:{{ config_location }}"
      #- "/opt/{{ service }}/logs:{{ log_location }}"
    restart_policy:
      unless-stopped
    interactive:
      no
    state:
      started
      
- name: Get infos on container
  docker_container_info:
    name: "{{ service }}"
  register: result

- name: Does container exist?
  debug:
    msg: "The {{service}} container {{ 'exists' if result.exists else 'does not exist' }}"

- name: Print the status of the container
  debug:
    msg: "The {{ service }} {{ result.container['State']['Pid'] }} container status is {{ result.container['State']['Status'] }}"
  when: result.exists
