---
- name: Pre Tasks
  hosts: "Service_{{ service }}"
  gather_facts: false
  pre_tasks:
  #
  - setup:

- name: "Deploy {{ service }}"
  hosts:  "Service_{{ service }}"
  roles:
  - { role: roles/common, "service={{ service }}", become: true }
  - { role: "roles/{{ service }}", "service=meme", become: true }
