---
- name: Pre Tasks
  hosts: "Service_{{ service }}"
  gather_facts: false
  pre_tasks:
  wait_for:
    port: 22
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    search_regex: OpenSSH
    delay: 30
  vars:
    ansible_connection: local
- setup:

- name: "Deploy {{ service }}"
  hosts:  "Service_{{ service }}"
  roles:
  - { role: roles/common, "service={{ service }}", become: true }
  - { role: "roles/{{ service }}", "service=meme", become: true }
