---
- name: Pre Tasks
  hosts: "Service_{{ service }}"
  pre_tasks:
    #- local_action: wait_for port=22 host={% if ansible_ssh_host is defined %}{{ ansible_ssh_host }}{% else %}{{ inventory_hostname }}{% endif %}
    - setup:

- name: "Deploy {{ service }}"
  hosts:  "Service_{{ service }}"
  roles:
  - { role: roles/common, "service={{ service }}", become: true }
  - { role: "roles/{{ service }}", "service=meme", become: true }
