---
- name: Pre Tasks
  hosts: "Service_{{ service }}"
  gather_facts: false
  become: true
  become_user: root
  pre_tasks:
  - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
    wait_for:
      port: 22
      host: '{{ (ansible_ssh_host|default(ansible_host))|default(Service_{{ service }}) }}'
      search_regex: OpenSSH
      delay: 10
    connection: local
  - setup:

- name: "Deploy {{ service }}"
  hosts:  "Service_{{ service }}"
  roles:
  - { role: roles/common, "service={{ service }}", become: true }
  - { role: "roles/{{ service }}", "service=meme", become: true }
