---
- name: Pre Tasks
  hosts: "Service_{{ service }}"
  gather_facts: false
  pre_tasks:
    - raw: sudo apt update&&sudo apt upgrade&& sudo apt install python3&& sudo apt install python&& sudo apt install -qy python-pip&& sudo pip install docker-py
    - setup:

- name: "Deploy {{ service }}"
  hosts: "Service_{{ service }}"
  roles:
  - { role: roles/common, "service={{ service }}","service_version={{service_version}}", become: true }
  - { role: "roles/{{ service }}", "service={{ service }}", "service_version={{service_version}}", become: true }
