---
- name: Pre Tasks
  hosts: "Service_{{ service }}"
  become: true
  gather_facts: false
  pre_tasks:
    - setup:
      register: setup_status
      until: setup_status is success
      delay: 10
      retries: 30


- name: "Deploy {{ service }}"
  hosts:  "Service_{{ service }}"
  become: true
  roles:
  - { role: roles/common, "service:{{ service }}" }
  -  role: "roles/{{ service }}" 
     vars: 
         service_version: "{{ serviceVersion }}"  
          dir: "roles/{{ service }}/vars" 
