---
- hosts: "Service_{{ service }}"
  gather_facts: false
 # tasks:  
#     - name: "error lock"
 #      shell: sudo apt -qy update 2>/dev/null | grep packages | cut -d '.' -f 1
    
- name: "Deploy {{ service }}"
  hosts: "Service_{{ service }}"
  gather_facts: false
  roles:
  - { role: roles/common, "service={{ service }}","service_version={{service_version}}", become: true }
  - { role: "roles/{{ service }}", "service={{ service }}", "service_version={{service_version}}", become: true }
