---
- name: Pre Tasks
  hosts: "Service_{{ service }}"
  gather_facts: false
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup:

- name: "Deploy {{ service }}"
  hosts: "Service_{{ service }}"
  roles:
  - { role: roles/common, "service={{ service }}","service_version={{service_version}}", become: true }
  - { role: "roles/{{ service }}", "service={{ service }}", "service_version={{service_version}}", become: true }
